export const API_ENDPOINTS = {
  OBSERVATIONS: '/api/observations',
  SUMMARIES: '/api/summaries',
  PROMPTS: '/api/prompts',
  SETTINGS: '/api/settings',
  PROVIDER_STATUS: '/api/providers/status',
  PROVIDER_DOCTOR: '/api/providers/doctor',
  PROVIDER_DISCOVER: '/api/providers/discover',
  PROVIDER_TEST: '/api/providers/test',
  PROVIDER_PROFILES: '/api/providers/profiles',
  PROVIDER_MODELS: (profileId: string) => `/api/providers/${encodeURIComponent(profileId)}/models`,
  PROVIDER_ACTIVATE: '/api/providers/activate',
  PROVIDER_SECRETS: '/api/providers/secrets',
  PROVIDER_IMPORT_CONNECTION: '/api/providers/import/connection',
  PROVIDER_IMPORT_PREVIEW: '/api/providers/import/preview',
  PROVIDER_IMPORT_PROFILES: '/api/providers/import/profiles',
  PRIVACY_SETTINGS: '/api/privacy/settings',
  STREAM: '/stream',
} as const;
